<a href="https://colab.research.google.com/github/murnuh/StockMarketML/blob/main/StocksTimeSeriesDownload.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
!git clone https://github.com/murnuh/StockMarketML.git

Cloning into 'StockMarketML'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 29 (delta 8), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (29/29), 474.77 KiB | 2.54 MiB/s, done.
Resolving deltas: 100% (8/8), done.

In [62]:
!ls

"dd'"   sample_data   StockMarketML

In [63]:
import pandas as pd

df = pd.read_csv('/content/StockMarketML/sp500_companies.csv')

In [64]:
df.Symbol

0       AAPL
1       MSFT
2       NVDA
3      GOOGL
4       GOOG
       ...
498      IVZ
499      BWA
500      WBA
501     PARA
502     BBWI
Name: Symbol, Length: 503, dtype: object

In [65]:
import pandas as pd
import datetime as dt
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import style
import yfinance as yf

%matplotlib inline

In [66]:
# Now let's define a range, that means, from when until when we want the data:
start_date= dt.datetime(1995, 1, 1) # the format is YYYY-MM-DD
end_date= dt.datetime(2024, 6, 1)

In [73]:
stocks_timeseries = pd.DataFrame()
for x in df.Symbol:
  df1 = yf.Ticker(x.strip()).history(start = start_date,end = end_date)
  stocks_timeseries = pd.concat([stocks_timeseries, df1.rename(columns = {'Open':x})[x]], axis = 1)

ERROR:yfinance:$SW: possibly delisted; no price data found  (1d 1995-01-01 00:00:00 -> 2024-06-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 788936400, endDate = 1717214400")

In [75]:
stocks_timeseries.tail(5)

,AAPL,MSFT,NVDA,GOOGL,GOOG,AMZN,META,BRK-B,LLY,AVGO,...,CZR,WYNN,GNRC,MOS,FMC,IVZ,BWA,WBA,PARA,BBWI
2024-05-24 00:00:00-04:00,188.601698,426.421420,104.431483,174.547785,176.087562,181.649994,466.710944,406.899994,806.872557,139.078497,...,32.700001,93.781667,145.110001,30.688149,59.895148,15.420086,35.137113,15.676048,11.745865,48.244646
2024-05-28 00:00:00-04:00,191.288587,428.857015,110.225520,174.019099,175.309480,179.929993,475.653527,408.239990,807.871151,140.092915,...,33.549999,94.080689,149.320007,30.619188,61.360112,15.459599,35.554464,15.656515,11.726058,47.858606
2024-05-29 00:00:00-04:00,189.390786,424.924108,113.031052,174.996675,176.376842,181.699997,473.737271,403.000000,801.879517,139.009942,...,32.762001,92.037404,148.979996,30.126601,61.558076,14.975561,35.147051,14.836085,11.726058,47.947693
2024-05-30 00:00:00-04:00,190.539446,423.536599,114.630774,174.767255,176.257148,181.309998,470.753073,403.769989,811.655877,137.012863,...,32.410000,92.216817,147.220001,29.308908,59.984233,15.103980,34.680015,14.572377,11.557693,48.313934
2024-05-31 00:00:00-04:00,191.218664,416.000198,112.501133,171.435495,172.975188,178.300003,464.894489,408.089996,817.657483,135.260219,...,32.380001,92.924497,149.500000,29.673423,60.578137,15.252155,34.888690,14.992358,11.775576,50.481676

In [76]:
stocks_timeseries.to_csv('stocksTimeSeries.csv')